name: VSC
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Git pull
      run: |
        cd
        git init
        git pull https://github.com/The-Unknow/RankingAPI-V2.git
        pip install -r requirements.txt
